### ISSUE TITLE
suggestion: decorator- / annotation-based prop/state declaration

### ISSUE THREAD

**Issue by akoenig** [reduct/component#7]
Awesome idea! :)

Just wanted to bring up an idea which came to me while reading the `README` :)
What do you think of defining the props as `es7.decorators`? Something like:

``` js
export default class FooComponent extends nodeProto.Component {

    @Prop({type: 'string', required: true})
    set myProp (prop) {
        this.myProp = prop;
    }

}
```

**Comment by Inkdpixels** [comment]
Whew - Great idea @akoenig, I didn't even considered that! 
I'm currently completing the basic API unit tests, and I don't know how soon I will be finished with them since I'm on vacation next week and there are some nasty bugs around ES6 & Jest. So bear in mind that it might take some time until I can implement such a syntax/API change. 

But.. If you've got some spare time - I would really appreciate a PR! :) :+1:

**Comment by Inkdpixels** [comment]
Just a quick note that this should also apply to the initial states which have been integrated in the upcoming v1.0.3.

**Comment by Inkdpixels** [comment]
Just a quick update: 
Wouldn't it make sense to attach the decorators onto the Class instead of the setters?

F.e.:

``` js
@Prop({type: 'string', required: true})
@Prop({type: 'string', required: true})
class FooComponent extends nodeProto.Component {
}
```

Reading the proposal for decorators, it states that each decorator needs a function/class on which it will be applied on. While the setter syntax has it's benefits, I would prefer the declaration without a setter function which needs to declared in each Class (reduced code/boilerplate).

Of course, this is just jibjab in my head right now, so dont take this post as serious as it looks.

**Comment by grebaldi** [comment]
I think, we could even keep the already present declarative syntax:

``` js
@Prop('myAwesomeProp').isString.isRequired
class StorchComponent extends nodeProto.Component {
}
```

**Comment by akoenig** [comment]
@grebaldi This is not possible, imho. Technical a decorator is just an ordinary function which will manipulate the `decorated` target (function).

**Comment by grebaldi** [comment]
just had a quick test:

``` js
function Foo() { console.log('foo got called'); }
function Bar() { console.log('bar got called'); }

const Annotations = { Foo, Bar };

@Annotations.Foo
@Annotations.Bar
class Storch {}

new Storch();
```

will output:

```
bar got called
foo got called
```

So, achievable imho. But still needs some research, if this is actual standard behavior^^

EDIT:

Now I got your point ^^ Probably the initial call of `@Prop('blubb')` wont work, since it might be considered finished then and couldn't return anything else then the decorated constructor... I'll figure something out :D

EDIT2: 

It works with `Foo` returning an object containing a function that itself returns the actual decorator _yay_ :dancers:

**Comment by Inkdpixels** [comment]
So basically both proposals:

``` javascript
class FooComponent extends component.Component {
    @Prop({name: 'myProp', type: Number, required: true})
    @Prop({name: 'myProp', type: {}, required: false})
    @Prop({name: 'myProp', type: 'string', required: true})
    constructor(el, props) {
    }
}
```

or:

``` javascript
class FooComponent extends component.Component {
    @Prop('myProp').type(Number).isRequired()
    @Prop('myObjectProp').type({}).isOptional()
    @Prop('myStringProp').type('string').isOptional()
    constructor(el, props) {
    }
}
```

I think both syntax proposals have their benefits:

The first one:
- Easier to write your own Prop-Decorator
- Less magic behinds the scenes
- Less readable

The second one:
- More readable
- Harder to write your own Prop-Decorator since you should have consistency, thus also need the chained methods.

**Comment by Inkdpixels** [comment]
Closed since this issue will be handled over at the nitpick library.
